Когда в рантайме встречается паника, поток выполнения программы сразу же переходит к вызову defer 
... и все defer отработают 
Поэтому, можно не только пользоваться recover, но и совершать другие действия - к примеру, закрывать файлы 
Однако, приложение упадет после отработки defer, т.к. паника не обработана recover

 Во втором кейсе с runtime.Goexit() мы завершаем горутину, но defer все равно отрабатывает 

 Что-то надоел defer, как от него избавиться?
 Есть только один способ - os.Exit()
 Просто берем и заканчиваем все 
