Да, в панику мы может пробросить nil 
Это эквивалентно new(runtime.PanicNilError)
В этом случае go любезно сообщит следующее: panic called with nil argument
И поскольку отрабатывает recover, программа продолжает работу 